# Generated by Django 3.2.8 on 2022-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Phone',
        ),
    ]
